# Generated by Django 4.0.4 on 2022-05-11 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='distance',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=10),
        ),
    ]
